keys:
  - &primary age127vmpu9ps2d2ulukcsp743xvmg5n9dsg9up4gtusc4ehgnjl6y7qg245jt
  - &orion age10tgzh4gyr2myps4y3zj63ppj8cmfmyyusvma9g6suzyn2tjz5gxqekmtls
  - &archinaut age1rnmn0c3sezwc2y90n66t740se98huva8w4hehyc2xlv32f8pnfssqkqsqj
  - &voyager age12g3sullwtjugy3f02cc4v5m6yt45qz9vt2muck2dnu9pqrfdmurs8jtu5s
  # TODO(netbird Phase-S): same as above, once telstar provisions.
  - &telstar age1PLACEHOLDER_REPLACE_ME_telstar_phase_s
creation_rules:
  - path_regex: secrets/sops/trend-installer\.sh$
    key_groups:
      - age:
          - *primary
          - *orion
          - *archinaut
  - path_regex: secrets/sops/secrets.yaml$
    key_groups:
      - age:
          - *primary
          - *orion
          - *archinaut
          - *voyager
