version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Check for updates every 24 hours
      - WATCHTOWER_POLL_INTERVAL=86400
      # Send notifications to a webhook (optional)
      # - WATCHTOWER_NOTIFICATION_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
      # - WATCHTOWER_NOTIFICATION_LEVEL=info
      # Clean up old images after updating
      - WATCHTOWER_CLEANUP=true
      # Include stopped containers
      - WATCHTOWER_INCLUDE_STOPPED=true
      # Don't update watchtower itself
      - WATCHTOWER_ROLLING_RESTART=true
    # Optional: Only watch specific containers
    # command: --label-enable
