_: {
  flake.modules.home.theming = {pkgs, ...}: {
    # GTK/Qt themes, colors, cursor and fonts are generated by Stylix from the
    # nix-colors base16 scheme (modules/desktop/stylix.nix + modules/theme.nix).
    # This module keeps only the non-colour bits Stylix doesn't own: the icon
    # theme and Nautilus behaviour. (Stylix enables `gtk`, so gtk.iconTheme just
    # merges in.)
    gtk = {
      iconTheme = {
        package = pkgs.papirus-icon-theme;
        name = "Papirus-Dark";
      };
      # Stylix generates the adw-gtk3 (light-named) theme but doesn't flip apps
      # to dark; this toggle does (GTK3 apps read it, GTK4/libadwaita read the
      # dconf color-scheme below).
      gtk3.extraConfig.gtk-application-prefer-dark-theme = true;
      gtk4.extraConfig.gtk-application-prefer-dark-theme = true;
    };

    dconf.settings = {
      "org/gnome/desktop/interface".color-scheme = "prefer-dark";
      # Nautilus (plan-B GUI file manager): right-click "Open in Terminal" → ghostty.
      "com/github/stunkymonkey/nautilus-open-any-terminal" = {
        terminal = "ghostty";
        new-tab = false;
        flatpak = "off";
      };
      "org/gnome/nautilus/preferences" = {
        default-folder-viewer = "list-view";
        show-hidden-files = true;
        show-delete-permanently = true;
        click-policy = "double";
      };
      "org/gtk/gtk4/settings/file-chooser" = {
        sort-directories-first = true;
        show-hidden = true;
      };
    };
  };
}
