_: {
  flake.modules.home.theming = {
    pkgs,
    lib,
    ...
  }: {
    # GTK/Qt themes, colors, cursor and fonts are generated by Stylix from the
    # nix-colors base16 scheme (modules/desktop/stylix.nix + modules/theme.nix).
    # This module keeps only the non-colour bits Stylix doesn't own: the icon
    # theme and Nautilus behaviour. (Stylix enables `gtk`, so gtk.iconTheme just
    # merges in.)
    gtk = {
      iconTheme = {
        package = pkgs.papirus-icon-theme;
        name = "Papirus-Dark";
      };
      # Stylix picks the light-named `adw-gtk3` + relies on prefer-dark. Apps
      # that read only the theme *name* (swappy, wxWidgets/OrcaSlicer, ...)
      # ignore prefer-dark and render light. Force the explicitly-dark variant;
      # Stylix's base16 colours still overlay via ~/.config/gtk-*/gtk.css.
      theme = lib.mkForce {
        package = pkgs.adw-gtk3;
        name = "adw-gtk3-dark";
      };
      # Belt-and-braces for GTK3/GTK4 apps that DO read the flag.
      gtk3.extraConfig.gtk-application-prefer-dark-theme = true;
      gtk4.extraConfig.gtk-application-prefer-dark-theme = true;
    };

    dconf.settings = {
      "org/gnome/desktop/interface".color-scheme = "prefer-dark";
      # Nautilus (plan-B GUI file manager): right-click "Open in Terminal" → ghostty.
      "com/github/stunkymonkey/nautilus-open-any-terminal" = {
        terminal = "ghostty";
        new-tab = false;
        flatpak = "off";
      };
      "org/gnome/nautilus/preferences" = {
        default-folder-viewer = "list-view";
        show-hidden-files = true;
        show-delete-permanently = true;
        click-policy = "double";
      };
      "org/gtk/gtk4/settings/file-chooser" = {
        sort-directories-first = true;
        show-hidden = true;
      };
    };
  };
}
