# yaml-language-server: $schema=https://schemas.recyclarr.dev/latest/config-schema.json
# https://recyclarr.dev/reference/config-reference/

# Sonarr
sonarr:
  sonarr:
    base_url: http://sonarr:8989
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: series
    quality_profiles:
      - name: WEB-1080p
        reset_unmatched_scores:
          enabled: true

# Radarr
radarr:
  radarr:
    base_url: http://radarr:7878
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_definition:
      type: movie
    quality_profiles:
      - name: HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
