# Specifies the network interface to use for the LocalIP readout
theme = "hydrogen"    

interface = "enp7s0"
long_uptime = true
long_shell = false
long_kernel = false
current_shell = true
physical_cores = true 

# Displays only the specified readouts.
# Accepted values (case-sensitive):
#   - Host
#   - Machine
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Resolution
#   - Backlight
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorLoad
#   - Memory
#   - Battery
# Example:
  show = ["Distribution", "Terminal", "DesktopEnvironment", "Shell"]
